# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            sideshowjack.uk
tagline:          'blog'
description:      'My blog about stuff'
url:              http://sideshowjack.uk/blog
baseurl:          '/blog'
production_url :  http://mrsideshowjack.github.io.com/blog
BASE_PATH :       http://sideshowjack.uk/blog

author:
  name:           'Jack Mason'
  url:            https://twitter.com/mrsideshowjack

paginate:         3

# Custom vars
version:          1

github:
  repo:           https://github.com/mrsideshowjack/mrsideshowjack.github.io
