# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            sideshowjack.uk
tagline:          'miss-sell'
description:      'My blog about stuff'
url:              http://sideshowjack.uk/miss-sell
baseurl:          '/miss-sell'
production_url :  http://mrsideshowjack.github.io.com/miss-sell
BASE_PATH :       http://sideshowjack.uk/miss-sell

author:
  name:           'Jack Mason'
  url:            https://twitter.com/mrsideshowjack

paginate:         3

# Custom vars
version:          1

github:
  repo:           https://github.com/mrsideshowjack/mrsideshowjack.github.io
